import { motion } from "framer-motion";
import { Github, ChevronDown } from "lucide-react";

const Hero = () => {
  return (
    <section className="relative flex min-h-screen flex-col items-center justify-center px-6 text-center">
      {/* Circuit trace decorations */}
      <div className="pointer-events-none absolute left-8 top-1/4 h-px w-32 bg-gradient-to-r from-transparent to-primary/30" />
      <div className="pointer-events-none absolute right-8 top-1/3 h-32 w-px bg-gradient-to-b from-transparent to-secondary/30" />
      <div className="pointer-events-none absolute bottom-1/4 left-1/4 h-px w-20 bg-gradient-to-r from-primary/20 to-transparent" />

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: "easeOut" }}
        className="max-w-4xl"
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1, duration: 0.5 }}
          className="mb-6 inline-block rounded-full border border-border bg-muted/50 px-4 py-1.5 font-mono text-xs text-muted-foreground"
        >
          <span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-primary animate-pulse-glow" />
          verilog-coder-3b · v1.0
        </motion.div>

        <h1 className="mb-6 text-5xl font-bold leading-tight tracking-tight text-foreground sm:text-6xl lg:text-7xl">
          Hardware Design,{" "}
          <span className="text-primary text-glow-green">Generated by AI.</span>
        </h1>

        <p className="mx-auto mb-10 max-w-2xl text-lg text-muted-foreground sm:text-xl">
          Fine-tuned on{" "}
          <span className="text-foreground font-medium">RTX 4050</span>.
          Optimized with{" "}
          <span className="text-secondary font-medium">QLoRA</span>.
          Capable of{" "}
          <span className="text-primary font-medium">Self-Checking Verification</span>.
        </p>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4, duration: 0.5 }}
          className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
        >
          <a
            href="https://github.com/Shrestha-Kumar/Verilog-Coder-3B"
            target="_blank"
            rel="noopener noreferrer"
            className="group inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 font-semibold text-primary-foreground transition-all hover:scale-105 glow-green"
          >
            <Github size={20} />
            View on GitHub
          </a>
          <a
            href="#playground"
            className="inline-flex items-center gap-2 rounded-lg border border-border bg-muted/30 px-6 py-3 font-medium text-foreground transition-all hover:border-primary/40 hover:bg-muted/50"
          >
            Try the Playground
          </a>
        </motion.div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.2, duration: 0.8 }}
        className="absolute bottom-8"
      >
        <ChevronDown size={24} className="animate-bounce text-muted-foreground" />
      </motion.div>
    </section>
  );
};

export default Hero;
